name: Build my frontend angular project 
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '20.x'
           cache: 'npm'
       - name: Build and Push the Created Docker Image to your Docker Repo
         uses: mr-smithers-excellent/docker-build-push@v6
         with:
          image: arkc0s/insa-chauffe-angular
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile

