name: Build my frontend angular project 
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '20.x'
           cache: 'npm'
       - name: Build and Push the Created Docker Image to your Docker Repo
         uses: mr-smithers-excellent/docker-build-push@v6
         with:
          image: arkc0s/insa-chauffe-angular
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
       - name: Setup SSH Key
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan insachauffe >> ~/.ssh/known_hosts
       - name: Tailscale
         uses: tailscale/github-action@v2
         with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
       - name: Deploy to Server
         run: |
          ssh -o StrictHostKeyChecking=no ubuntu@insachauffe
          "docker system prune -a &&
          docker volume ls|grep frontend_volume > /dev/null || docker volume create frontend_volume &&
          docker stop myfrontend &&
          docker rm myfrontend &&
          docker run --rm -v frontend_volume:/data/ ubuntu /bin/sh -c     "rm -rf /data/*" &&
          docker pull arkc0s/insa-chauffe-angular:latest && 
          docker run -d --name myfrontend -v frontend_volume:/var/www/html/ arkc0s/insa-chauffe-angular:latest && 
          docker system prune -af"
  


